### ISSUE TITLE
[BUG] Error: marked(): input parameter is of type [object Array], string expected

### ISSUE THREAD

**Issue by alexander-fenster** [compodoc/compodoc#1102]
In v1.1.14, the following happens when I run `npx compodoc src/` on https://github.com/googleapis/gax-nodejs repository:

```
Unhandled Rejection at: Promise {
  <rejected> Error: marked(): input parameter is of type [object Array], string expected
      at marked (/Users/fenster/repos/gax-nodejs/node_modules/marked/src/marked.js:27:11)
      at /Users/fenster/repos/gax-nodejs/node_modules/@compodoc/compodoc/dist/index-cli-32a621dc.js:600:23
      at arrayEach (/Users/fenster/repos/gax-nodejs/node_modules/lodash/lodash.js:530:11)
      at Object.forEach (/Users/fenster/repos/gax-nodejs/node_modules/lodash/lodash.js:9410:14)
      at markedtags (/Users/fenster/repos/gax-nodejs/node_modules/@compodoc/compodoc/dist/index-cli-32a621dc.js:599:18)
      at AngularDependencies.visitFunctionDeclaration (/Users/fenster/repos/gax-nodejs/node_modules/@compodoc/compodoc/dist/index-cli-32a621dc.js:9559:32)
      at parseNode (/Users/fenster/repos/gax-nodejs/node_modules/@compodoc/compodoc/dist/index-cli-32a621dc.js:8984:43)
      at /Users/fenster/repos/gax-nodejs/node_modules/@compodoc/compodoc/dist/index-cli-32a621dc.js:9260:13
      at visitNodes (/Users/fenster/repos/gax-nodejs/node_modules/@ts-morph/common/dist/typescript.js:29004:30)
      at Object.forEachChild (/Users/fenster/repos/gax-nodejs/node_modules/@ts-morph/common/dist/typescript.js:29243:24)
} reason: Error: marked(): input parameter is of type [object Array], string expected
    at marked (/Users/fenster/repos/gax-nodejs/node_modules/marked/src/marked.js:27:11)
    at /Users/fenster/repos/gax-nodejs/node_modules/@compodoc/compodoc/dist/index-cli-32a621dc.js:600:23
    at arrayEach (/Users/fenster/repos/gax-nodejs/node_modules/lodash/lodash.js:530:11)
    at Object.forEach (/Users/fenster/repos/gax-nodejs/node_modules/lodash/lodash.js:9410:14)
    at markedtags (/Users/fenster/repos/gax-nodejs/node_modules/@compodoc/compodoc/dist/index-cli-32a621dc.js:599:18)
    at AngularDependencies.visitFunctionDeclaration (/Users/fenster/repos/gax-nodejs/node_modules/@compodoc/compodoc/dist/index-cli-32a621dc.js:9559:32)
    at parseNode (/Users/fenster/repos/gax-nodejs/node_modules/@compodoc/compodoc/dist/index-cli-32a621dc.js:8984:43)
    at /Users/fenster/repos/gax-nodejs/node_modules/@compodoc/compodoc/dist/index-cli-32a621dc.js:9260:13
    at visitNodes (/Users/fenster/repos/gax-nodejs/node_modules/@ts-morph/common/dist/typescript.js:29004:30)
    at Object.forEachChild (/Users/fenster/repos/gax-nodejs/node_modules/@ts-morph/common/dist/typescript.js:29243:24)
[14:43:21] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
```

##### **Operating System, Node.js, npm, compodoc version(s)**

MacOS and Linux, Node.js v15.11.0 (but fails on other versions in CI too), npm v7.6.0.
compodoc v1.1.13: OK
compodoc v1.1.14: fails

##### **Angular configuration, a `package.json` file in the root folder**

No Angular. `package.json`: https://github.com/googleapis/gax-nodejs/blob/e5b2e63b7d3e028c17c1229e6eb547a70e9f4a62/package.json

##### **Compodoc installed globally or locally ?**

Locally as a dev dependency

##### **If possible your terminal logs before the error**

https://gist.github.com/alexander-fenster/3e0aaf1220d2774c4c649260c475a41d

##### **Reproduce the error**

```
$ git clone https://github.com/googleapis/gax-nodejs.git
$ cd gax-nodejs
$ git checkout e5b2e63b7d3e028c17c1229e6eb547a70e9f4a62
$ npm install
$ npx compodoc src/
```

**Comment by vogloblinsky** [comment]
Can i have the source code of src/gax.ts ?

**Comment by Smootium** [comment]
Also experiencing this issue (with our private repo/code base). I will use ver 1.1.13 for now, as well

**Comment by daeteck** [comment]
Also having this issue. Version 1.1.12 and 1.1.13 are not working properly with Storybook in an Angular project and I was hopping to have that issue fixed in the version 1.1.14 but it seems that it is not the case.

I will have to stay in the version 1.1.11 in my case.

**Comment by vogloblinsky** [comment]
Fixed by https://github.com/compodoc/compodoc/commit/40870b387300c27c0ca1be983159cbfc7518de00

**Comment by TheSlimvReal** [comment]
I have installed compodoc version `1.1.15` and the issue still exists

**Comment by vogloblinsky** [comment]
do you have an example of code where it breaks ?

**Comment by TheSlimvReal** [comment]
Thanks for still paying attention to this issue.

It breaks at the following file and only if I remove both comments it works 
```
@UntilDestroy()
export class EntitySelectComponent<E extends Entity> {
  @Input() selectionInputType: "id" | "entity" = "id";
  @Output() selectionChange = new EventEmitter<(string | E)[]>();

  /**
   * The entity-type (e.g. 'Child', 'School', e.t.c.) to set.
   * The entity-type has to be inside {@link ENTITY_MAP}
   * @param type The ENTITY_TYPE of a Entity. This affects the entities which will be loaded and the component
   *             that displays the entities.
   * @throws Error when `type` is not in the entity-map
   */
  @Input() set entityType(type: string) {}

  /**
   * The (initial) selection. Can be used in combination with {@link selectionChange}
   * to enable two-way binding to either an array of entities or an array of strings
   * corresponding to the id's of the entities.
   * The type (id's or entities) will be determined by the setting of the
   * {@link selectionInputType}
   * @param sel The initial selection
   */
  @Input() set selection(sel: (string | E)[]) {}
}
```

When I remove the `{@link ...}` annotations it also works. The moment I include a single link the build breaks.

**Comment by vogloblinsky** [comment]
Fixed by https://github.com/compodoc/compodoc/commit/33aa835ccdadb032ba7ffef0f38fc6033392640b

**Comment by TheSlimvReal** [comment]
Great, thank you so much. I am looking forward to the next release
