### ISSUE TITLE
[BUG] Strange output in terminal. Runs endlessly.

### ISSUE THREAD

**Issue by mavidulin** [compodoc/compodoc#1173]
##### **Overview of the issue**
When installing any version of compodoc and running any compodoc command (e.g. "npx compodoc -V"), there seems to be a script running endlessly and outputting very strange things.

It's possible the issue is "colors" dependency. See this article https://snyk.io/blog/open-source-npm-packages-colors-faker/

##### **Operating System, Node.js, npm, compodoc version(s)**
MacOS Big Sur
Nodejs v14
npm 6.14.15
compodoc version: any

##### **Compodoc installed globally or locally ?**
Locally installed

**Comment by vogloblinsky** [comment]
Try to install 1.1.17 version please, it should be fixed with that version.

**Comment by mavidulin** [comment]
Thanks for the fast answer, however, the issue remains with version 1.1.17. In package.json inside node_modules/@compodoc/compodoc I also see the "colors" dependency.

**Comment by mavidulin** [comment]
> Thanks for the fast answer, however, the issue remains with version 1.1.17. In package.json inside node_modules/@compodoc/compodoc I also see the "colors" dependency.

I can further confirm that the "colors" is pinned to version "1.4.0" which should apparently be unaffected, but strangely I still have the problem.

**Comment by vogloblinsky** [comment]
I am on it

**Comment by vogloblinsky** [comment]
Ok, fixed with compodoc 1.1.18

**Comment by Pluiesurlavitre** [comment]
Thank you @vogloblinsky :)

**Comment by koen-dev** [comment]
Thank you @vogloblinsky 🎉
