### ISSUE TITLE
[BUG] : graph generation error with spaces in folder path

### ISSUE THREAD

**Issue by vogloblinsky** [compodoc/compodoc#44]
##### **Overview of the issue**

if the project path contains spaces, the graph generation breaks with this stacktrace: 

```
Error during graph generation: : 'C:\Users\IEUser\Documents\www\tests-compodoc\test' is not recognized as an internal or external command,
operable program or batch file.
```

##### **Operating System, Node.js, npm Version(s)**

Windows 7, node.js 7.0.0, npm 3.10.8

##### **Compodoc installed globally or locally ?**

compodoc locally

##### **Reproduce the error**

npm run doc

**Comment by nadhir-falta** [comment]
still seeing this error on release 0.0.31

**Comment by vogloblinsky** [comment]
Ok, reproduced. My last test was with compodoc installed globally, and not locally.

**Comment by nadhir-falta** [comment]
@vogloblinsky First, Thank you so much for the tool, it is great, especially with the addition of the coverage hurry to that.
The only problem is that I still get this:
```
Error during graph generation: : 'C:\Program Files ' is not recognized as an internal or external command,
operable program or batch file.
```

 "compodoc": "0.0.33", installed both globally and locally.

Thanks again for the hard work

**Comment by vogloblinsky** [comment]
Can i have more information about your context ?
Versions etc ?

**Comment by nadhir-falta** [comment]
npm 3.10.6
node 5.5.0
angular 2.4.1
typescript 2.1.4
compodoc 0.0.33 (installed globally and locally)
path C:\Program Files (x86)\Jenkins\workspace\myProject    (Notice the space in the path)

I think  issue is the special characters in the path.

**Comment by vogloblinsky** [comment]
Ok thanks reproduced.

**Comment by nadhir-falta** [comment]
I'm still getting this error with 0.0.34
**If installed globally AND locally I get:**
```
Error during graph generation: : 'C:\Program Files ' is not recognized as an internal or external command,
operable program or batch file.
```

**If installed globally only I get:  (issue #65)**
`Error during graph generation: : The system cannot find the path specified.`

**If installed Locally only I get:**
```
Error during graph generation: : 'C:\Program Files ' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by nadhir-falta** [comment]
@vogloblinsky any news with this bug.

**Comment by vogloblinsky** [comment]
Reproduced in my VM Windows, try to fix it this afternoon.

**Comment by nadhir-falta** [comment]
@vogloblinsky thanks man I appreciate that.
Merci.

**Comment by vogloblinsky** [comment]
Fixed in 0.0.38

**Comment by nadhir-falta** [comment]
@vogloblinsky sorry to say this but I still get the same errors with --version 0.0.38

**Comment by vogloblinsky** [comment]
@nadhir-falta 
Ok. 
Could you re-test by using angular-cli, generate a fresh project in `C:\Program Files (x86)\Jenkins\workspace\`
and run compodoc on it : `compodoc -p src/tsconfig.json -s`
Thanks

**Comment by nadhir-falta** [comment]
@vogloblinsky I tried that and that's what I get:
```
### [10:06:05] parsing        : C:/Program Files (x86)/Jenkins/workspace/PFM-UI-Docs/TestCompodoc/src/environments/environment.prod.ts
[10:06:06] parsing        : C:/Program Files (x86)/Jenkins/workspace/PFM-UI-Docs/TestCompodoc/src/environments/environment.ts
[10:06:06] parsing        : C:/Program Files (x86)/Jenkins/workspace/PFM-UI-Docs/TestCompodoc/src/main.ts
[10:06:08] parsing        : C:/Program Files (x86)/Jenkins/workspace/PFM-UI-Docs/TestCompodoc/src/polyfills.ts
[10:06:11] parsing        : C:/Program Files (x86)/Jenkins/workspace/PFM-UI-Docs/TestCompodoc/src/test.ts
[10:06:12] Prepare modules
[10:06:12] Prepare components
[10:06:12] Process documentation coverage report
[10:06:12] Process pages
[10:06:12] Process page   : index
[10:06:12] Process page   : overview
[10:06:12] Process page   : modules
[10:06:12] Process page   : AppModule
[10:06:12] Process page   : AppComponent
[10:06:12] Process page   : coverage
[10:06:12] Copy main resources
[10:06:12] Process main graph
[10:06:12] Error during graph generation: : The system cannot find the path specified.
```

**Comment by vogloblinsky** [comment]
Ok, can i have all your configuration ?
OS, node/npm versions, compodoc global ?
Thanks

**Comment by nadhir-falta** [comment]
npm 3.10.6
node 5.5.0
angular 2.4.1
typescript 2.1.4
compodoc 0.0.38 (installed globally and locally)
path C:\Program Files (x86)\Jenkins\workspace\myProject

**Comment by nadhir-falta** [comment]
@vogloblinsky any news about this one ?

**Comment by vogloblinsky** [comment]
Yes, we have integrated ngd inside @compodoc scope on npm, and last version 0.0.39 doesn't call ngd with a cli call.
Could you upgrade and made a new test ?

**Comment by nadhir-falta** [comment]
@vogloblinsky Yessss, it is fixed now.
Thank you so much for all this.
Great job on building this tool.

**Comment by vogloblinsky** [comment]
:+1: :smiley:
