### ISSUE TITLE
[BUG] Routes Parsing Error with path defined in const.

### ISSUE THREAD

**Issue by chunghha** [compodoc/compodoc#51]
##### **Overview of the issue**

I have app level config file for const as seen in this commit
https://github.com/chunghha/clarity-seed/commit/006663f8e5bef23c71844036ad7255ff83796ab2

if I use the APP_CONFIG in the routes, compodoc throws this error while parsing.
"Routes parsing error, maybe a trailing comma ?"

##### **Operating System, Node.js, npm, compodoc version(s)**
Linux(ubuntu16.04)
node: 7.3.0
npm: 3.10.10

##### **Angular configuration, a `package.json` file in the root folder**
please see the package.json in the repository.

##### **Compodoc installed globally or locally ?**
locally.

##### **Motivation for or Use Case**

The Routes is parsed without error if I don't use APP_CONFIG ( as good one with master branch, https://chunghha.github.io/clarity-seed/routes.html ) and nothing wrong to use the APP_CONFIG for the app to run. Thus, compodoc should parse the Routes without this error.

##### **Reproduce the error**

please check out the compodoc branch to reproduce this error.

**Comment by vogloblinsky** [comment]
After AST parsing, Compodoc tries to recreate the code in memory for handling routes, and use JSON.parse for recreating the array.
Seems your APP_CONFIG which is an external variable breaks this.
I have to better handling the routes with all the current situation and code like yours.
Keep in touch.

**Comment by vogloblinsky** [comment]
@chunghha just starting fixing this bug and example repository not available. Is https://github.com/chunghha/clarity the new one ?

**Comment by chunghha** [comment]
https://github.com/chunghha/example-app/commit/fab5711c63bbb1c832a07b8abc56242e06235698

I didn't realize that the clarity-seed is needed here when it's removed. Please use this example-app repo (**compodoc branch**) for your fixing.

One thing I noticed is that

- This, without Routes type, doesn't get the parsing error but skips RouterModule to the generated compodoc document.
`export const appRoutes = [`

- This, with Routes type, gets the parsing error.
`export const appRoutes: Routes = [`

**Comment by vogloblinsky** [comment]
Thanks @chunghha, it helps me adding another parsing context for Routes definition.
Yes "Routes" type is mandatory for routes parsing.

**Comment by AilisObrian** [comment]
@chunghha OMG! I LOVE YOU!!!!! It resolved my issue!

**Comment by vogloblinsky** [comment]
@ailisobrian can you explain a little ?

**Comment by vogloblinsky** [comment]
Fixed with 1.0.5

**Comment by mail2bhramar** [comment]
Using Version compodoc 1.0.5 . Still getting the following error 
`Routes parsing error, maybe a trailing comma or an external variable, trying to fix that later after sources scanning`

**Comment by vogloblinsky** [comment]
@mail2bhramar 
Did you have an example of routing for your project ?
